jenkins

diff --git a/80-cdn/Jenkinsfile b/80-cdn/Jenkinsfile
--- a/80-cdn/Jenkinsfile
+++ b/80-cdn/Jenkinsfile
@@ -10,15 +10,15 @@ pipeline {
     options {
         timeout(time: 30, unit: 'MINUTES')
         disableConcurrentBuilds()
-        
+        ansiColor('xterm')
     }
 
     stages {
-        stage('INIT and PLAN') { 
+        stage('INIT and PLAN') {
             steps {
                 withAWS(credentials: 'aws-cred', region: 'us-east-1') {
-                    sh  """
-                        cd 00-vpc
+                    sh """
+                        cd 80-cdn
                         terraform init -reconfigure
                         terraform plan -out=tfplan
                     """
@@ -26,36 +26,47 @@ pipeline {
             }
         }
 
-        stage('Apply or Destroy') { 
+        stage('Apply or Destroy') {
             steps {
                 withAWS(credentials: 'aws-cred', region: 'us-east-1') {
-                    sh  """
-                        cd 00-vpc
-                        
+                    sh """
+                        cd 80-cdn 
                         if [ "${params.ACTION}" = "apply" ]; then
                             terraform apply -auto-approve tfplan
                         elif [ "${params.ACTION}" = "destroy" ]; then
                             terraform destroy -auto-approve
                         fi
                     """
-                       
                 }
             }
         }
 
-        stage('Trigger SG') {
-             when{
-                expression { params.ACTION == 'apply' }
+         stage('Destroy'){
+            when {
+                expression { params.ACTION == 'destroy' }
             }
-            steps {
-                build job: '10-sg', wait: false, parameters: [
-                    string(name: 'ACTION', value: "${params.ACTION}")
-                ]
+            steps{
+                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
+                    script {
+                        def directories = ['80-cdn', '70-ecr', '60-alb', '50-acm', '40-eks', '30-rds', '20-bastion', '10-sg', '00-vpc']
+                        for (dir in directories) {
+                            echo "Destroying resources in directory: ${dir}"
+                            sh """
+                            cd ${dir}
+                            terraform init -reconfigure
+                            terraform destroy -auto-approve || { echo "Failed to destroy resources in ${dir}"; exit 1; }
+                            cd ..
+                            """
+                        }
+            }
+                }
             }
         }
-    }
 
-    post { 
+        
+        }
+
+    post {
         always {
             deleteDir()
         }
